name: CML & DVC
on: [push]
jobs:
  train-and-report:
    runs-on: [ubuntu-latest]
    steps:
      - uses: iterative/setup-cml@v2
      - uses: iterative/setup-dvc@v1
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:          
          python-version: '3.x'
      - name: Train model
        run: |
          dvc get https://github.com/iterative/dataset-registry \
          get-started/data.xml -o data/data.xml
          pip install -r src/requirements.txt
          dvc repro
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          run: |
          # Compare metrics to main
          git fetch --depth=1 origin main:main 
          dvc metrics diff --show-md main >> report.md
          # Plot training loss function diff
          dvc plots diff \
            --target loss.csv --show-vega main > vega.json
          vl2png vega.json > plot.png
          echo '![](./plot.png "Training Loss")' >> report.md
          cml comment create report.md
